version: '3'

services:
  app:
    build: .
    container_name: google_analytics_conn
    ports:
      - "8020:15200"
    restart: always
    command: bash -c "uvicorn main:app --reload --host 0.0.0.0 --port 15200"
    env_file:
      - .env
