"""empty message

Revision ID: f7508a467453
Revises: 
Create Date: 2022-05-06 14:33:55.002017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7508a467453'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ga_transactions_dev',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(length=40), nullable=True),
    sa.Column('host_name', sa.String(), nullable=True),
    sa.Column('source_medium', sa.String(), nullable=True),
    sa.Column('campaign', sa.String(length=256), nullable=True),
    sa.Column('keyword', sa.String(length=256), nullable=True),
    sa.Column('device', sa.String(length=120), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('transaction', sa.Integer(), nullable=True),
    sa.Column('value', sa.DECIMAL(), nullable=True),
    sa.Column('index', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('index', name='transaction_index')
    )
    op.create_table('ga_users_dev',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(length=40), nullable=True),
    sa.Column('host_name', sa.String(), nullable=True),
    sa.Column('source_medium', sa.String(), nullable=True),
    sa.Column('campaign', sa.String(length=256), nullable=True),
    sa.Column('keyword', sa.String(length=256), nullable=True),
    sa.Column('device', sa.String(length=120), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('users', sa.Integer(), nullable=True),
    sa.Column('sessions', sa.Integer(), nullable=True),
    sa.Column('index', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('index', name='user_index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ga_users_dev')
    op.drop_table('ga_transactions_dev')
    # ### end Alembic commands ###
